name: apply

on:
  workflow_run:
    workflows: build
    types: completed

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git branch
  status:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - uses: LouisBrunner/checks-action@v1.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Apply
          conclusion: success
