name: destroy
on: delete # workflow_dispatch enables the destruction of protected branches
concurrency: terraform-${{ github.event.ref }}

permissions:
  id-token: write # required for aws-actions/configure-aws-credentials

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11 # https://github.com/python/cpython/tags
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6 # https://github.com/hashicorp/terraform/tags
          terraform_wrapper: false
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ROLE_NAME }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - uses: champ-oss/action-terraform-config@develop
        with:
          branch: ${{ github.event.ref }}
      - run: terraform init
      - run: terraform destroy -auto-approve
