name: destroy
on: delete # workflow_dispatch enables the destruction of protected branches

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo destroy {{ github.event.workflow_run.branch }}
