name: dispatch

on:
  workflow_run:
    workflows: [ build, apply ]
    types: completed

env:
  BRANCH: ${{ github.event.workflow_run.branch }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name == 'build' }}
    steps:
      - run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${ACTION_TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OWNER/REPO/actions/workflows/apply.yml/dispatches \
            -d '{"ref":"${BRANCH}"}'
  apply:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name == 'apply' }}
    steps:
      - run: echo "trigger test"
