name: dispatch

on:
  workflow_run:
    workflows: [ build, apply ]
    types: completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name == github.job }}
    steps:
      - run: echo "trigger apply"
  apply:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name == github.job }}
    steps:
      - run: echo "trigger test"
