name: dispatch

on:
  workflow_run:
    workflows: [ build, apply ]
    types: completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name == env.GITHUB_JOB }}
    steps:
      - run: echo "trigger apply"
      - run: env
  apply:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name == 'apply' }}
    steps:
      - run: echo "trigger test"
