name: pool

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ build ]
    types: [ requested ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git branch
