name: summary
on: pull_request

env:
  CONTEXT: ${{ toJSON(github) }}

permissions:
  id-token: write # required for aws-actions/configure-aws-credentials
  pull-requests: write # required for champ-oss/terraform-pr-summary

defaults:
  run:
    working-directory: terraform

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11 # https://github.com/python/cpython/tags
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6 # https://github.com/hashicorp/terraform/tags
          terraform_wrapper: false
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ROLE_NAME }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - uses: champ-oss/action-terraform-config@develop
        with:
          branch: ${{ github.event.repository.default_branch }}
      - run: terraform init
      - run: terraform validate
      - uses: champ-oss/terraform-pr-summary@develop
        with:
          working-directory: terraform
