name: test

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ build ]
    types: [ completed ]
    branches-ignore: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - run: git branch
